[workspace]
resolver = '2'
members = ["space-shooter", "load-gltf", "map-3d"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
bevy = "0.12"
rand = "0.8"

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
codegen-units = 1
strip = "debuginfo"
